# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kyle/nasa/dev/HDTN

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kyle/nasa/dev/HDTN/rtp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kyle/nasa/dev/HDTN/rtp/CMakeFiles /home/kyle/nasa/dev/HDTN/rtp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kyle/nasa/dev/HDTN/rtp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bp_app_patterns_lib

# Build rule for target.
bp_app_patterns_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bp_app_patterns_lib
.PHONY : bp_app_patterns_lib

# fast build rule for target.
bp_app_patterns_lib/fast:
	$(MAKE) -f common/bpcodec/CMakeFiles/bp_app_patterns_lib.dir/build.make common/bpcodec/CMakeFiles/bp_app_patterns_lib.dir/build
.PHONY : bp_app_patterns_lib/fast

#=============================================================================
# Target rules for targets named bpcodec

# Build rule for target.
bpcodec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bpcodec
.PHONY : bpcodec

# fast build rule for target.
bpcodec/fast:
	$(MAKE) -f common/bpcodec/CMakeFiles/bpcodec.dir/build.make common/bpcodec/CMakeFiles/bpcodec.dir/build
.PHONY : bpcodec/fast

#=============================================================================
# Target rules for targets named bpsendfile

# Build rule for target.
bpsendfile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bpsendfile
.PHONY : bpsendfile

# fast build rule for target.
bpsendfile/fast:
	$(MAKE) -f common/bpcodec/apps/CMakeFiles/bpsendfile.dir/build.make common/bpcodec/apps/CMakeFiles/bpsendfile.dir/build
.PHONY : bpsendfile/fast

#=============================================================================
# Target rules for targets named bpsink-async

# Build rule for target.
bpsink-async: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bpsink-async
.PHONY : bpsink-async

# fast build rule for target.
bpsink-async/fast:
	$(MAKE) -f common/bpcodec/apps/CMakeFiles/bpsink-async.dir/build.make common/bpcodec/apps/CMakeFiles/bpsink-async.dir/build
.PHONY : bpsink-async/fast

#=============================================================================
# Target rules for targets named bpreceivefile

# Build rule for target.
bpreceivefile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bpreceivefile
.PHONY : bpreceivefile

# fast build rule for target.
bpreceivefile/fast:
	$(MAKE) -f common/bpcodec/apps/CMakeFiles/bpreceivefile.dir/build.make common/bpcodec/apps/CMakeFiles/bpreceivefile.dir/build
.PHONY : bpreceivefile/fast

#=============================================================================
# Target rules for targets named bping

# Build rule for target.
bping: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bping
.PHONY : bping

# fast build rule for target.
bping/fast:
	$(MAKE) -f common/bpcodec/apps/CMakeFiles/bping.dir/build.make common/bpcodec/apps/CMakeFiles/bping.dir/build
.PHONY : bping/fast

#=============================================================================
# Target rules for targets named bpgen-async

# Build rule for target.
bpgen-async: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bpgen-async
.PHONY : bpgen-async

# fast build rule for target.
bpgen-async/fast:
	$(MAKE) -f common/bpcodec/apps/CMakeFiles/bpgen-async.dir/build.make common/bpcodec/apps/CMakeFiles/bpgen-async.dir/build
.PHONY : bpgen-async/fast

#=============================================================================
# Target rules for targets named telemetry_definitions

# Build rule for target.
telemetry_definitions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 telemetry_definitions
.PHONY : telemetry_definitions

# fast build rule for target.
telemetry_definitions/fast:
	$(MAKE) -f common/telemetry_definitions/CMakeFiles/telemetry_definitions.dir/build.make common/telemetry_definitions/CMakeFiles/telemetry_definitions.dir/build
.PHONY : telemetry_definitions/fast

#=============================================================================
# Target rules for targets named log_lib

# Build rule for target.
log_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 log_lib
.PHONY : log_lib

# fast build rule for target.
log_lib/fast:
	$(MAKE) -f common/logger/CMakeFiles/log_lib.dir/build.make common/logger/CMakeFiles/log_lib.dir/build
.PHONY : log_lib/fast

#=============================================================================
# Target rules for targets named hdtn_util

# Build rule for target.
hdtn_util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hdtn_util
.PHONY : hdtn_util

# fast build rule for target.
hdtn_util/fast:
	$(MAKE) -f common/util/CMakeFiles/hdtn_util.dir/build.make common/util/CMakeFiles/hdtn_util.dir/build
.PHONY : hdtn_util/fast

#=============================================================================
# Target rules for targets named config_lib

# Build rule for target.
config_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 config_lib
.PHONY : config_lib

# fast build rule for target.
config_lib/fast:
	$(MAKE) -f common/config/CMakeFiles/config_lib.dir/build.make common/config/CMakeFiles/config_lib.dir/build
.PHONY : config_lib/fast

#=============================================================================
# Target rules for targets named cgr_lib

# Build rule for target.
cgr_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgr_lib
.PHONY : cgr_lib

# fast build rule for target.
cgr_lib/fast:
	$(MAKE) -f common/cgr/CMakeFiles/cgr_lib.dir/build.make common/cgr/CMakeFiles/cgr_lib.dir/build
.PHONY : cgr_lib/fast

#=============================================================================
# Target rules for targets named induct_manager_lib

# Build rule for target.
induct_manager_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 induct_manager_lib
.PHONY : induct_manager_lib

# fast build rule for target.
induct_manager_lib/fast:
	$(MAKE) -f common/induct_manager/CMakeFiles/induct_manager_lib.dir/build.make common/induct_manager/CMakeFiles/induct_manager_lib.dir/build
.PHONY : induct_manager_lib/fast

#=============================================================================
# Target rules for targets named outduct_manager_lib

# Build rule for target.
outduct_manager_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 outduct_manager_lib
.PHONY : outduct_manager_lib

# fast build rule for target.
outduct_manager_lib/fast:
	$(MAKE) -f common/outduct_manager/CMakeFiles/outduct_manager_lib.dir/build.make common/outduct_manager/CMakeFiles/outduct_manager_lib.dir/build
.PHONY : outduct_manager_lib/fast

#=============================================================================
# Target rules for targets named tcpcl_lib

# Build rule for target.
tcpcl_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tcpcl_lib
.PHONY : tcpcl_lib

# fast build rule for target.
tcpcl_lib/fast:
	$(MAKE) -f common/tcpcl/CMakeFiles/tcpcl_lib.dir/build.make common/tcpcl/CMakeFiles/tcpcl_lib.dir/build
.PHONY : tcpcl_lib/fast

#=============================================================================
# Target rules for targets named ltp-file-transfer

# Build rule for target.
ltp-file-transfer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ltp-file-transfer
.PHONY : ltp-file-transfer

# fast build rule for target.
ltp-file-transfer/fast:
	$(MAKE) -f common/ltp/CMakeFiles/ltp-file-transfer.dir/build.make common/ltp/CMakeFiles/ltp-file-transfer.dir/build
.PHONY : ltp-file-transfer/fast

#=============================================================================
# Target rules for targets named ltp_lib

# Build rule for target.
ltp_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ltp_lib
.PHONY : ltp_lib

# fast build rule for target.
ltp_lib/fast:
	$(MAKE) -f common/ltp/CMakeFiles/ltp_lib.dir/build.make common/ltp/CMakeFiles/ltp_lib.dir/build
.PHONY : ltp_lib/fast

#=============================================================================
# Target rules for targets named stcp_lib

# Build rule for target.
stcp_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stcp_lib
.PHONY : stcp_lib

# fast build rule for target.
stcp_lib/fast:
	$(MAKE) -f common/stcp/CMakeFiles/stcp_lib.dir/build.make common/stcp/CMakeFiles/stcp_lib.dir/build
.PHONY : stcp_lib/fast

#=============================================================================
# Target rules for targets named udp_lib

# Build rule for target.
udp_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 udp_lib
.PHONY : udp_lib

# fast build rule for target.
udp_lib/fast:
	$(MAKE) -f common/udp/CMakeFiles/udp_lib.dir/build.make common/udp/CMakeFiles/udp_lib.dir/build
.PHONY : udp_lib/fast

#=============================================================================
# Target rules for targets named stats_lib

# Build rule for target.
stats_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stats_lib
.PHONY : stats_lib

# fast build rule for target.
stats_lib/fast:
	$(MAKE) -f common/stats_logger/CMakeFiles/stats_lib.dir/build.make common/stats_logger/CMakeFiles/stats_lib.dir/build
.PHONY : stats_lib/fast

#=============================================================================
# Target rules for targets named telem_cmd_interface

# Build rule for target.
telem_cmd_interface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 telem_cmd_interface
.PHONY : telem_cmd_interface

# fast build rule for target.
telem_cmd_interface/fast:
	$(MAKE) -f module/telem_cmd_interface/CMakeFiles/telem_cmd_interface.dir/build.make module/telem_cmd_interface/CMakeFiles/telem_cmd_interface.dir/build
.PHONY : telem_cmd_interface/fast

#=============================================================================
# Target rules for targets named telem_lib

# Build rule for target.
telem_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 telem_lib
.PHONY : telem_lib

# fast build rule for target.
telem_lib/fast:
	$(MAKE) -f module/telem_cmd_interface/CMakeFiles/telem_lib.dir/build.make module/telem_cmd_interface/CMakeFiles/telem_lib.dir/build
.PHONY : telem_lib/fast

#=============================================================================
# Target rules for targets named storage-speedtest

# Build rule for target.
storage-speedtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 storage-speedtest
.PHONY : storage-speedtest

# fast build rule for target.
storage-speedtest/fast:
	$(MAKE) -f module/storage/CMakeFiles/storage-speedtest.dir/build.make module/storage/CMakeFiles/storage-speedtest.dir/build
.PHONY : storage-speedtest/fast

#=============================================================================
# Target rules for targets named storage_lib

# Build rule for target.
storage_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 storage_lib
.PHONY : storage_lib

# fast build rule for target.
storage_lib/fast:
	$(MAKE) -f module/storage/CMakeFiles/storage_lib.dir/build.make module/storage/CMakeFiles/storage_lib.dir/build
.PHONY : storage_lib/fast

#=============================================================================
# Target rules for targets named hdtn-storage

# Build rule for target.
hdtn-storage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hdtn-storage
.PHONY : hdtn-storage

# fast build rule for target.
hdtn-storage/fast:
	$(MAKE) -f module/storage/CMakeFiles/hdtn-storage.dir/build.make module/storage/CMakeFiles/hdtn-storage.dir/build
.PHONY : hdtn-storage/fast

#=============================================================================
# Target rules for targets named hdtn-ingress

# Build rule for target.
hdtn-ingress: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hdtn-ingress
.PHONY : hdtn-ingress

# fast build rule for target.
hdtn-ingress/fast:
	$(MAKE) -f module/ingress/CMakeFiles/hdtn-ingress.dir/build.make module/ingress/CMakeFiles/hdtn-ingress.dir/build
.PHONY : hdtn-ingress/fast

#=============================================================================
# Target rules for targets named ingress_async_lib

# Build rule for target.
ingress_async_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ingress_async_lib
.PHONY : ingress_async_lib

# fast build rule for target.
ingress_async_lib/fast:
	$(MAKE) -f module/ingress/CMakeFiles/ingress_async_lib.dir/build.make module/ingress/CMakeFiles/ingress_async_lib.dir/build
.PHONY : ingress_async_lib/fast

#=============================================================================
# Target rules for targets named hdtn-egress-async

# Build rule for target.
hdtn-egress-async: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hdtn-egress-async
.PHONY : hdtn-egress-async

# fast build rule for target.
hdtn-egress-async/fast:
	$(MAKE) -f module/egress/CMakeFiles/hdtn-egress-async.dir/build.make module/egress/CMakeFiles/hdtn-egress-async.dir/build
.PHONY : hdtn-egress-async/fast

#=============================================================================
# Target rules for targets named egress_async_lib

# Build rule for target.
egress_async_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 egress_async_lib
.PHONY : egress_async_lib

# fast build rule for target.
egress_async_lib/fast:
	$(MAKE) -f module/egress/CMakeFiles/egress_async_lib.dir/build.make module/egress/CMakeFiles/egress_async_lib.dir/build
.PHONY : egress_async_lib/fast

#=============================================================================
# Target rules for targets named hdtn-scheduler

# Build rule for target.
hdtn-scheduler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hdtn-scheduler
.PHONY : hdtn-scheduler

# fast build rule for target.
hdtn-scheduler/fast:
	$(MAKE) -f module/scheduler/CMakeFiles/hdtn-scheduler.dir/build.make module/scheduler/CMakeFiles/hdtn-scheduler.dir/build
.PHONY : hdtn-scheduler/fast

#=============================================================================
# Target rules for targets named scheduler_lib

# Build rule for target.
scheduler_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scheduler_lib
.PHONY : scheduler_lib

# fast build rule for target.
scheduler_lib/fast:
	$(MAKE) -f module/scheduler/CMakeFiles/scheduler_lib.dir/build.make module/scheduler/CMakeFiles/scheduler_lib.dir/build
.PHONY : scheduler_lib/fast

#=============================================================================
# Target rules for targets named hdtn-router

# Build rule for target.
hdtn-router: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hdtn-router
.PHONY : hdtn-router

# fast build rule for target.
hdtn-router/fast:
	$(MAKE) -f module/router/CMakeFiles/hdtn-router.dir/build.make module/router/CMakeFiles/hdtn-router.dir/build
.PHONY : hdtn-router/fast

#=============================================================================
# Target rules for targets named router_lib

# Build rule for target.
router_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 router_lib
.PHONY : router_lib

# fast build rule for target.
router_lib/fast:
	$(MAKE) -f module/router/CMakeFiles/router_lib.dir/build.make module/router/CMakeFiles/router_lib.dir/build
.PHONY : router_lib/fast

#=============================================================================
# Target rules for targets named hdtn_one_process_lib

# Build rule for target.
hdtn_one_process_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hdtn_one_process_lib
.PHONY : hdtn_one_process_lib

# fast build rule for target.
hdtn_one_process_lib/fast:
	$(MAKE) -f module/hdtn_one_process/CMakeFiles/hdtn_one_process_lib.dir/build.make module/hdtn_one_process/CMakeFiles/hdtn_one_process_lib.dir/build
.PHONY : hdtn_one_process_lib/fast

#=============================================================================
# Target rules for targets named hdtn-one-process

# Build rule for target.
hdtn-one-process: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hdtn-one-process
.PHONY : hdtn-one-process

# fast build rule for target.
hdtn-one-process/fast:
	$(MAKE) -f module/hdtn_one_process/CMakeFiles/hdtn-one-process.dir/build.make module/hdtn_one_process/CMakeFiles/hdtn-one-process.dir/build
.PHONY : hdtn-one-process/fast

#=============================================================================
# Target rules for targets named udp-delay-sim

# Build rule for target.
udp-delay-sim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 udp-delay-sim
.PHONY : udp-delay-sim

# fast build rule for target.
udp-delay-sim/fast:
	$(MAKE) -f module/udp_delay_sim/CMakeFiles/udp-delay-sim.dir/build.make module/udp_delay_sim/CMakeFiles/udp-delay-sim.dir/build
.PHONY : udp-delay-sim/fast

#=============================================================================
# Target rules for targets named udp_delay_sim_lib

# Build rule for target.
udp_delay_sim_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 udp_delay_sim_lib
.PHONY : udp_delay_sim_lib

# fast build rule for target.
udp_delay_sim_lib/fast:
	$(MAKE) -f module/udp_delay_sim/CMakeFiles/udp_delay_sim_lib.dir/build.make module/udp_delay_sim/CMakeFiles/udp_delay_sim_lib.dir/build
.PHONY : udp_delay_sim_lib/fast

#=============================================================================
# Target rules for targets named unit-tests

# Build rule for target.
unit-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit-tests
.PHONY : unit-tests

# fast build rule for target.
unit-tests/fast:
	$(MAKE) -f tests/unit_tests/CMakeFiles/unit-tests.dir/build.make tests/unit_tests/CMakeFiles/unit-tests.dir/build
.PHONY : unit-tests/fast

#=============================================================================
# Target rules for targets named integrated-tests

# Build rule for target.
integrated-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 integrated-tests
.PHONY : integrated-tests

# fast build rule for target.
integrated-tests/fast:
	$(MAKE) -f tests/integrated_tests/CMakeFiles/integrated-tests.dir/build.make tests/integrated_tests/CMakeFiles/integrated-tests.dir/build
.PHONY : integrated-tests/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... bp_app_patterns_lib"
	@echo "... bpcodec"
	@echo "... bpsendfile"
	@echo "... bpsink-async"
	@echo "... bpreceivefile"
	@echo "... bping"
	@echo "... bpgen-async"
	@echo "... telemetry_definitions"
	@echo "... log_lib"
	@echo "... hdtn_util"
	@echo "... config_lib"
	@echo "... cgr_lib"
	@echo "... induct_manager_lib"
	@echo "... outduct_manager_lib"
	@echo "... tcpcl_lib"
	@echo "... ltp-file-transfer"
	@echo "... ltp_lib"
	@echo "... stcp_lib"
	@echo "... udp_lib"
	@echo "... stats_lib"
	@echo "... telem_cmd_interface"
	@echo "... telem_lib"
	@echo "... storage-speedtest"
	@echo "... storage_lib"
	@echo "... hdtn-storage"
	@echo "... hdtn-ingress"
	@echo "... ingress_async_lib"
	@echo "... hdtn-egress-async"
	@echo "... egress_async_lib"
	@echo "... hdtn-scheduler"
	@echo "... scheduler_lib"
	@echo "... hdtn-router"
	@echo "... router_lib"
	@echo "... hdtn_one_process_lib"
	@echo "... hdtn-one-process"
	@echo "... udp-delay-sim"
	@echo "... udp_delay_sim_lib"
	@echo "... unit-tests"
	@echo "... integrated-tests"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

